name: GitHub Actions Demo
run-name: Run unit tests
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit test
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: bun ci
      - run: bun spec
