name: GitHub Actions Demo
run-name: Run unit tests
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit test
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run spec

      - uses: actions/setup-go@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
      - name: Deploy using Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd ./deployment/production && terraform init && bun run deploy
