name: GitHub Actions Demo
run-name: Run unit tests
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit test
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run spec

      - run: sudo apt install packer
      - run: bun run image

