name: GitHub Actions Demo
run-name: Run unit tests
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit test
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run spec

      - uses: actions/setup-go@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: mkdir ./deployment/.ssh
      - run: ssh-keygen -q -f ./deployment/.ssh -N "" -O no-touch-required -t rsa 
      - run: cd ./deployment/production && terraform init
      - run: cd ./deployment/production && terraform destroy -auto-approve
      - run: cd ./deployment/production && terraform apply -auto-approve
