name: GitHub Actions Demo
run-name: Run unit tests
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit test
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run spec

      - uses: actions/setup-go@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          TF_VAR_SSH_PVT_KEY: ${{ secrets.SSH_PVT_KEY }}
      - run: cd ./deployment/production
      - run: terraform init
      - run: terraform destroy -auto-approve
      - run: terraform apply -auto-approve
